export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const RESET_ERRORS = "RESET_ERRORS";

export const MOVIE_ADD_START = "MOVIE_ADD_START";
export const MOVIE_ADD_SUCCESS = "MOVIE_ADD_SUCCESS";
export const MOVIE_ADD_FAILED = "MOVIE_ADD_FAILED";

export const MOVIE_GET_START = "MOVIE_GET_START";
export const MOVIE_GET_SUCCESS = "MOVIE_GET_SUCCESS";
export const MOVIE_GET_FAILED = "MOVIE_GET_FAILED";

export const MOVIES_GET_START = "MOVIES_GET_START";
export const MOVIES_GET_SUCCESS = "MOVIES_GET_SUCCESS";
export const MOVIES_GET_FAILED = "MOVIES_GET_FAILED";

export const MOVIE_EDIT_START = "MOVIE_EDIT_START";
export const MOVIE_EDIT_SUCCESS = "MOVIE_EDIT_SUCCESS";
export const MOVIE_EDIT_FAILED = "MOVIE_EDIT_FAILED";

export const MOVIE_DELETE_START = "MOVIE_DELETE_START";
export const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS";
export const MOVIE_DELETE_FAILED = "MOVIE_DELETE_FAILED";